create table if not exists audits (
  id uuid primary key,
  result jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists leads (
  id bigint generated by default as identity primary key,
  audit_id uuid references audits(id),
  email text not null,
  company_name text,
  role text,
  team_size integer,
  created_at timestamptz not null default now()
);

create index if not exists leads_audit_id_idx on leads(audit_id);
